version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"   # API do MinIO
      - "9001:9001"   # Interface Web do MinIO
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./app
    container_name: backend
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "password"
      BUCKET_NAME: "uploads"
    ports:
      - "5000:5000"
    depends_on:
      - minio

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  minio_data: